name: cerati
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_secure_storage: ^9.0.0
  flutter_udid: ^3.0.0
  get_storage: ^2.1.1
  go_router: ^13.0.1
  image_picker: ^1.0.7
  in_app_review: ^2.0.8
  internet_connectivity_checker: ^1.0.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^3.0.0
  package_info_plus: ^6.0.0
  sentry: ^7.15.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  freezed: ^2.4.6
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
