name: cerati
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  dio: ^5.2.1+1
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_secure_storage: ^8.0.0
  flutter_udid: ^2.0.1
  go_router: ^9.0.0
  image_picker: ^1.0.0
  in_app_review: ^2.0.6
  internet_connectivity_checker: ^1.0.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  lottie: ^2.4.0
  package_info_plus: ^4.0.2
  sentry: ^7.8.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1
  freezed: ^2.3.5
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
