# Exclude C/C++/Objective-C files from analysis
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
# Basic project settings
sonar.projectKey=cerati
sonar.projectName=cerati
sonar.projectVersion=2.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_e88a08d7ea924f3f11e9aa9d14119868811e7141
# Define your source directories
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
# Set the Dart plugin as the default language
sonar.language=dart
# LCOV report for your code's coverage
# Ensure you generate the lcov report when running tests
#sonar.dart.coverage.reportPaths=coverage/lcov.info
# If you have certain patterns you want to exclude, you can use:
#sonar.exclusions=**/*_mock.dart,**/*.g.dart
#sonar.inclusions=**/*.dart
#sonar.test.inclusions=test/**/*.dart
# If your Flutter project has Android and iOS code and you want SonarQube to analyze those as well:
# sonar.sources=lib,android/app/src,ios/Runner



