name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-dart:
    uses: ./.github/workflows/dart_package.yml
    with:
      setup: dart --version
      platform: "vm,chrome"


  verify-flutter:
    uses: ./.github/workflows/flutter_package.yml
    with:
      flutter_channel: stable
      flutter_version: 3.10.5
      setup: flutter doctor --verbose

#  verify-pana-dart:
#    uses: ./.github/workflows/pana.yml
#    with:
#      min_score: 95
#
#
#  verify-pana-flutter:
#    uses: ./.github/workflows/pana.yml
#    with:
#      min_score: 95


  build:
    needs:
      [
        verify-dart,
        verify-flutter,
#        verify-pana-dart,
#        verify-pana-flutter,
      ]

    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'
